driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  resource_cloning: false

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
 - name: default
   run_list:
   - recipe[snort::default]
