driver:
  name: vagrant
  chef_version: current

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3 CHEF_VERSION=12.19.36
  - name: centos-7.3
  # - name: debian-7.11 remove until Debian Vagrant box is fixed
  - name: debian-8.7
  - name: fedora-25
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
 - name: default
   run_list:
   - recipe[test::default]
   attributes:
      oink_code: <%= ENV['SNORT_LICENCE'] %>
      community_rules_url: <%= ENV['COMMUNITY_URL'] %>
